apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
  annotations:
    # ArgoCD Image Updater
    argocd-image-updater.argoproj.io/image-list: webapp=ghcr.io/maikereis/web-app
    argocd-image-updater.argoproj.io/webapp.update-strategy: latest
    argocd-image-updater.argoproj.io/webapp.allow-tags: regexp:^master-.*$
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: webapp
        image: ghcr.io/maikereis/web-app:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5