apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 # same as containerPort in ./deployment.yaml
    nodePort: 30100
