apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo/configmap.yaml
  - mongo/deployment.yaml
  - mongo/secret.yaml
  - mongo/service.yaml
  - webapp/deployment.yaml
  - webapp/service.yaml
  - webapp/servicemonitor.yaml
  - ghcr-pull-secret.yaml